workflows:
  ios_ipa_unsigned:
    name: iOS — Unsigned IPA (auto-create platforms + force artifacts)
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Bootstrap Flutter project
        script: |
          set -e
          flutter --version
          flutter create .
          flutter pub get
      - name: iOS deps (CocoaPods)
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock || true
          pod repo update
          pod install
          cd ..
      - name: Add iOS usage descriptions (camera/photos)
        script: |
          set -e
          INFO_PLIST="ios/Runner/Info.plist"
          /usr/libexec/PlistBuddy -c "Add :NSPhotoLibraryUsageDescription string This app needs photo library access to pick chart images." "$INFO_PLIST" || \
          /usr/libexec/PlistBuddy -c "Set :NSPhotoLibraryUsageDescription This app needs photo library access to pick chart images." "$INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Add :NSCameraUsageDescription string This app may use the camera to capture chart images." "$INFO_PLIST" || \
          /usr/libexec/PlistBuddy -c "Set :NSCameraUsageDescription This app may use the camera to capture chart images." "$INFO_PLIST"
      - name: Build unsigned IPA
        script: |
          set -e
          flutter build ipa --release --no-codesign \
            --build-name=1.0.0 --build-number=$(date +%Y%m%d%H%M)
      - name: Collect artifacts (IPA / APP)
        script: |
          set -e
          mkdir -p artifacts
          echo "=== List build/ios ==="
          ls -R build/ios || true
          # حاول نسخ أي IPA لمجلد artifacts
          if compgen -G "build/ios/ipa/*.ipa" > /dev/null; then
            cp build/ios/ipa/*.ipa artifacts/
          fi
          # فشل؟ دور على أي ipa في كل build/
          if [ -z "$(ls -A artifacts 2>/dev/null)" ]; then
            find build -name "*.ipa" -maxdepth 5 -print -exec cp {} artifacts/ \;
          fi
          # كحل أخير: لو ما في IPA، خد .app كملف zip (يشتغل مع Sideloadly أحيانًا)
          if [ -z "$(ls -A artifacts 2>/dev/null)" ]; then
            APP_PATH=$(find build/ios -name "*.app" -type d -print -quit)
            if [ -n "$APP_PATH" ]; then
              (cd "$(dirname "$APP_PATH")" && zip -r ../../artifacts/MDA.app.zip "$(basename "$APP_PATH")")
            fi
          fi
          echo "=== List artifacts ==="
          ls -la artifacts || true
    artifacts:
      - artifacts/*.ipa
      - artifacts/*.zip

  android_release:
    name: Android — Release APK (auto-create platforms)
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Bootstrap & build
        script: |
          set -e
          flutter --version
          flutter create .
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
